---
driver:
  name: vagrant
  vm_hostname: iis  

provisioner:
  name: chef_zero

verifier:
  name: inspec  

transport:
  name: winrm
  elevated: true
  username: Administrator
  password: Pass@word1  

platforms:
  - name: Windows2012R2
    driver:
      box: mwrock/Windows2012R2
      customize:
        memory: 2048

suites:
  - name: iis
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
